name: swd_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1

  flutter:
    sdk: flutter

  rxdart: 0.20.0
  carousel_slider: ^2.0.0
  smooth_star_rating: ^1.1.1
  flutter_svg: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.4.2
  flutter_sticky_header: ^0.3.4
  json_annotation: ^3.0.1
  date_picker_timeline: ^1.2.0
  translator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/homeLogo.png
    - assets/javaSubject.jpg
    - assets/pic1.jpg
    - assets/pic2.jpg
    - assets/p4.jpg
    - assets/Dash-Diet.jpg
    - assets/eat-clean.jpg
    - assets/low-carb.jpg
    - assets/ruler.png
    - assets/weight.png
    - assets/food-set.png
    - assets/fitfoodvn.png
    - assets/fitfood1.jpg
    - assets/logo-fitfood.png
    - assets/Balme-logo.png
    - assets/avatar.jpg
    - assets/background-avatar.jpg
    - assets/welcome1.jpg
    - assets/input-name.png
    - assets/fit1.jpg
    - assets/fit3.jpg
    - assets/fit2.jpg
    - assets/restaurant1.jpg
    - assets/restaurant2.jpg
    - assets/restaurant3.jpg
    - assets/ship.jpg
    - assets/food1.png
    - assets/food22.png
    - assets/location.png
    - assets/paleo.jpg
    # - assets/restaurant4.jgp
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
